In [1]:
import numpy as np

In [2]:
def slowDFT(t):
    N = t.shape[0]
    omega = np.zeros(N, dtype=np.complex_)
    for n in range(N):
        omega[n] = sum(t[m] * np.exp(-1j*2*np.pi*m*n/N) for m in range(N))
    return omega

In [3]:
def slowInvDFT(omega):
    N = omega.shape[0]
    t = np.zeros(N, dtype=np.complex_)
    for m in range(N):
        t[m] = sum(omega[n] * np.exp(1j*2*np.pi*m*n/N) for n in range(N)) / N
    return t

In [4]:
slowDFT(np.array([0, -1.5, -3., -1.5, 0, 1.5, 3., 1.5, 0.]))

array([ 0.        +0.j        , -3.56907786+9.80596084j,
        1.54813333-1.84499346j,  2.25      -1.29903811j,
       -0.22905547+0.04038866j, -0.22905547-0.04038866j,
        2.25      +1.29903811j,  1.54813333+1.84499346j,
       -3.56907786-9.80596084j])

In [5]:
slowInvDFT(slowDFT(np.array([0, -1.5, -3., -1.5, 0, 1.5, 3., 1.5, 0.])))

array([ 3.94745964e-15-1.18423789e-15j, -1.50000000e+00-3.05928122e-15j,
       -3.00000000e+00+1.97372982e-16j, -1.50000000e+00-4.93432455e-16j,
        9.39063642e-16+7.89491929e-16j,  1.50000000e+00+5.92118946e-16j,
        3.00000000e+00-1.03620816e-15j,  1.50000000e+00-1.57898386e-15j,
       -2.96059473e-16+3.55271368e-15j])

In [6]:
slowDFT(np.array([.25, .75, .75, .25, -.25, -.75, -.75, -.25]))

array([ 0.00000000e+00+0.00000000e+00j,  1.20710678e+00-2.91421356e+00j,
       -1.14888010e-16+5.55111512e-17j, -2.07106781e-01+8.57864376e-02j,
        0.00000000e+00+0.00000000e+00j, -2.07106781e-01-8.57864376e-02j,
        2.12102087e-15+4.44089210e-16j,  1.20710678e+00+2.91421356e+00j])

In [7]:
slowInvDFT(slowDFT(np.array([.25, .75, .75, .25, -.25, -.75, -.75, -.25])))

array([ 0.25+1.66533454e-16j,  0.75-2.22044605e-16j,
        0.75+1.66533454e-16j,  0.25+2.22044605e-16j,
       -0.25+5.55111512e-17j, -0.75+3.88578059e-16j,
       -0.75-5.55111512e-16j, -0.25+8.88178420e-16j])