In [1]:
import numpy as np

In [17]:
def FFT(f):
    nbdata = f.shape[0]
    assert np.log(nbdata) / np.log(2) % 1 == 0.0
    
    if nbdata == 1:
        return f

    x = FFT(f[0::2])
    y = FFT(f[1::2])

    g = np.zeros(nbdata, dtype=np.complex_)
    for i in range(nbdata // 2):
        w = np.exp(-1j*2*np.pi*i/nbdata)
        g[i] = x[i] + w * y[i]
        g[i+nbdata//2] = x[i] - w * y[i]

    return g

In [24]:
def invFFTrecursive(f):
    nbdata = f.shape[0]
    assert np.log(nbdata) / np.log(2) % 1 == 0.0
    
    if nbdata == 1:
        return f

    x = invFFTrecursive(f[0::2])
    y = invFFTrecursive(f[1::2])

    g = np.zeros(nbdata, dtype=np.complex_)
    for i in range(nbdata // 2):
        w = np.exp(1j*2*np.pi*i/nbdata)
        g[i] = x[i] + w * y[i]
        g[i+nbdata//2] = x[i] - w * y[i]

    return g

def invFFT(f):
    nbdata = f.shape[0]
    return invFFTrecursive(f) / nbdata

In [25]:
FFT(np.array([.25, .75, .75, .25, -.25, -.75, -.75, -.25]))

array([ 0.        +0.j        ,  1.20710678-2.91421356j,
        0.        +0.j        , -0.20710678+0.08578644j,
        0.        +0.j        , -0.20710678-0.08578644j,
        0.        +0.j        ,  1.20710678+2.91421356j])

In [26]:
invFFT(FFT(np.array([.25, .75, .75, .25, -.25, -.75, -.75, -.25])))

array([ 0.25+0.00000000e+00j,  0.75+0.00000000e+00j,
        0.75+2.34646841e-17j,  0.25+0.00000000e+00j,
       -0.25+0.00000000e+00j, -0.75+0.00000000e+00j,
       -0.75-2.34646841e-17j, -0.25+0.00000000e+00j])

In [28]:
np.real(invFFT(FFT(np.array([.25, .75, .75, .25, -.25, -.75, -.75, -.25]))))

array([ 0.25,  0.75,  0.75,  0.25, -0.25, -0.75, -0.75, -0.25])

In [30]:
np.testing.assert_array_equal(np.array([0., 1.]), np.array([0., 2.]))

AssertionError: 
Arrays are not equal

Mismatched elements: 1 / 2 (50%)
Max absolute difference: 1.
Max relative difference: 0.5
 x: array([0., 1.])
 y: array([0., 2.])